FROM telegraf:1.21.4

ARG INFLUX_URL
ARG INFLUX_TOKEN
ARG INFLUX_ORG

ENV INFLUX_URL=${INFLUX_URL}
ENV INFLUX_TOKEN=${INFLUX_TOKEN}
ENV INFLUX_ORG=${INFLUX_ORG}

COPY ./telegraf.conf /etc/telegraf/telegraf.conf
