FROM telegraf:1.21.4

ARG AMQP_BROKER
ARG AMQP_USERNAME
ARG AMQP_PASSWORD

ARG INFLUX_URL
ARG INFLUX_TOKEN
ARG INFLUX_ORG

ENV AMQP_BROKER=${AMQP_BROKER}
ENV AMQP_USERNAME=${AMQP_USERNAME}
ENV AMQP_PASSWORD=${AMQP_PASSWORD}

ENV INFLUX_URL=${INFLUX_URL}
ENV INFLUX_TOKEN=${INFLUX_TOKEN}
ENV INFLUX_ORG=${INFLUX_ORG}

COPY ./telegraf.conf /etc/telegraf/telegraf.conf
